import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
	ArrowLeft,
	Banknote,
	CheckCircle2,
	ChevronDown,
	Clock3,
	Hourglass,
	LockKeyhole,
	MapPinned,
	Pencil,
	Trophy,
	UsersRound,
} from 'lucide-react';
import { api } from '../../api';
import PremiumHeader from '../common/PremiumHeader';
import '../home/Home.css';
import './BrowseRooms.css';
import './CreatePrivateRoom.css';

const FALLBACK_BOARDS = {
	builtin: [{ id: 'world-tour', name: 'World Tour', builtin: true }],
	mine: [],
	community: [],
};

export default function CreatePrivateRoom({ pushToast }) {
	const nav = useNavigate();
	const [boards, setBoards] = useState(FALLBACK_BOARDS);
	const [selectedBoardId, setSelectedBoardId] = useState('world-tour');
	const [boardsLoading, setBoardsLoading] = useState(true);
	const [boardError, setBoardError] = useState('');
	const [creating, setCreating] = useState(false);

	useEffect(() => {
		let isCurrent = true;
		api.listBoards()
			.then((nextBoards) => {
				if (!isCurrent) return;
				setBoards({
					builtin: nextBoards.builtin?.length
						? nextBoards.builtin
						: FALLBACK_BOARDS.builtin,
					mine: nextBoards.mine || [],
					community: nextBoards.community || [],
				});
				setBoardError('');
			})
			.catch(() => {
				if (isCurrent)
					setBoardError('Custom boards are unavailable. World Tour is selected.');
			})
			.finally(() => {
				if (isCurrent) setBoardsLoading(false);
			});
		return () => {
			isCurrent = false;
		};
	}, []);

	const selectedBoard = useMemo(
		() =>
			[...boards.builtin, ...boards.mine, ...boards.community].find(
				(board) => board.id === selectedBoardId,
			) || FALLBACK_BOARDS.builtin[0],
		[boards, selectedBoardId],
	);

	function savedIdentity() {
		return {
			username: (localStorage.getItem('monopoly.username') || '').trim(),
			color: localStorage.getItem('monopoly.color') || '#EF4444',
		};
	}

	async function createRoom(event) {
		event.preventDefault();
		const identity = savedIdentity();
		if (!identity.username) {
			pushToast('Enter your nickname on the home page first', 'error');
			nav('/');
			return;
		}
		if (creating) return;
		setCreating(true);
		try {
			const boardPayload = selectedBoard.builtin
				? { boardId: selectedBoard.id }
				: { boardId: 'world-tour', customBoardId: selectedBoard.id };
			const { roomCode } = await api.createRoom({ ...identity, ...boardPayload });
			nav(`/r/${roomCode}`);
		} catch (requestError) {
			pushToast(requestError.message || 'Failed to create room', 'error');
			setCreating(false);
		}
	}

	return (
		<main className="app-page landing-page create-private-page">
			<PremiumHeader pushToast={pushToast} showLogo onLogoClick={() => nav('/')} />

			<div className="create-private-shell">
				<button
					className="browse-back-button"
					type="button"
					onClick={() => nav('/private-rooms')}
				>
					<ArrowLeft aria-hidden="true" /> Back
				</button>

				<header className="create-private-title">
					<h1>Create private room</h1>
					<p>Customize your room settings and invite your friends.</p>
				</header>

				<form className="create-private-form" onSubmit={createRoom}>
					<fieldset>
						<legend>Room settings</legend>
						<div className="create-settings-grid">
							<SettingInput
								label="Room name"
								icon={Pencil}
								placeholder="Enter room name..."
								unavailable
							/>
							<SettingInput
								label="Room code (optional)"
								icon={LockKeyhole}
								placeholder="Enter custom code..."
								help="A random code will be generated by the server"
								unavailable
							/>
							<SettingSelect
								label="Select board"
								icon={MapPinned}
								value={selectedBoardId}
								onChange={setSelectedBoardId}
								help={boardError}
								disabled={boardsLoading}
								status={boardsLoading ? 'Loading' : ''}
							>
								{boards.builtin.length > 0 && (
									<optgroup label="Built-in boards">
										{boards.builtin.map((board) => (
											<option key={board.id} value={board.id}>
												{board.name}
											</option>
										))}
									</optgroup>
								)}
								{boards.mine.length > 0 && (
									<optgroup label="My boards">
										{boards.mine.map((board) => (
											<option key={board.id} value={board.id}>
												{board.name}
											</option>
										))}
									</optgroup>
								)}
								{boards.community.length > 0 && (
									<optgroup label="Community boards">
										{boards.community.map((board) => (
											<option key={board.id} value={board.id}>
												{board.name}
											</option>
										))}
									</optgroup>
								)}
							</SettingSelect>
							<SettingSelect
								label="Max players"
								icon={UsersRound}
								value="8"
								disabled
								status="Server default"
							>
								<option value="8">8 Players</option>
							</SettingSelect>
						</div>
					</fieldset>

					<fieldset className="create-settings-section">
						<legend>Game settings</legend>
						<div className="create-settings-grid">
							<SettingSelect
								label="Game mode"
								icon={Trophy}
								value="classic"
								disabled
								status="Server default"
							>
								<option value="classic">Classic Board</option>
							</SettingSelect>
							<SettingSelect
								label="Starting cash"
								icon={Banknote}
								value="1500"
								disabled
								status="Server default"
							>
								<option value="1500">1500</option>
							</SettingSelect>
							<SettingSelect
								label="Time limit"
								icon={Clock3}
								value="none"
								disabled
								status="Server default"
							>
								<option value="none">No Limit</option>
							</SettingSelect>
							<SettingSelect
								label="Turn timer"
								icon={Hourglass}
								value="none"
								disabled
								status="Server default"
							>
								<option value="none">No Limit</option>
							</SettingSelect>
						</div>
					</fieldset>

					<fieldset className="create-privacy-section">
						<legend>Room privacy</legend>
						<label className="create-privacy-option">
							<input type="radio" checked readOnly />
							<span className="create-privacy-icon" aria-hidden="true">
								<LockKeyhole />
							</span>
							<span className="create-privacy-copy">
								<strong>Private room</strong>
								<small>
									Share the generated room code with players you want to invite
								</small>
							</span>
							<CheckCircle2 aria-hidden="true" />
						</label>
					</fieldset>

					<button
						className="create-private-submit"
						type="submit"
						disabled={creating || boardsLoading}
						aria-busy={creating}
					>
						<LockKeyhole aria-hidden="true" />
						{creating ? 'Creating room...' : 'Create private room'}
					</button>
					<p className="create-private-footnote">
						You’ll be able to invite players after creating the room.
					</p>
				</form>
			</div>
		</main>
	);
}

function SettingInput({ label, icon: Icon, placeholder, help, unavailable = false }) {
	return (
		<label className="create-setting-field">
			<span>
				{label}
				{unavailable && <small>Coming soon</small>}
			</span>
			<span className={`create-setting-control${unavailable ? ' is-unavailable' : ''}`}>
				<Icon aria-hidden="true" />
				<input disabled={unavailable} placeholder={placeholder} />
			</span>
			{help && <small className="create-setting-help">{help}</small>}
		</label>
	);
}

function SettingSelect({
	label,
	icon: Icon,
	value,
	onChange,
	children,
	help,
	disabled = false,
	status = '',
}) {
	return (
		<label className="create-setting-field">
			<span>
				{label}
				{status && <small>{status}</small>}
			</span>
			<span className={`create-setting-control${disabled ? ' is-unavailable' : ''}`}>
				<Icon aria-hidden="true" />
				<select
					value={value}
					onChange={(event) => onChange?.(event.target.value)}
					disabled={disabled}
				>
					{children}
				</select>
				<ChevronDown aria-hidden="true" />
			</span>
			{help && <small className="create-setting-help">{help}</small>}
		</label>
	);
}
